# Generated by Django 5.1.4 on 2025-03-31 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='canal',
            name='imagen_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
