# Generated by Django 5.1.4 on 2025-03-31 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paquetes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paquete',
            name='incluye_telefonia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paquete',
            name='velocidad_internet',
            field=models.CharField(default='50 Mbps', max_length=50),
        ),
    ]
